# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crossing1',
            old_name='camera_id',
            new_name='cam',
        ),
    ]
