# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170729_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapp',
            name='created_on',
            field=models.CharField(max_length=20),
        ),
    ]
