# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170729_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crossing1',
            name='density',
        ),
        migrations.AddField(
            model_name='crossing1',
            name='conclusion',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
