# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170729_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossing1',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=234),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mapp',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
