# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20170729_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crossing1',
            name='created_on',
        ),
    ]
