# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20170730_0411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crossing1',
            old_name='cam_id',
            new_name='camera_id',
        ),
        migrations.RenameField(
            model_name='stray1',
            old_name='cam_id',
            new_name='camera_id',
        ),
    ]
